name: Node.js test

on:
  push:
    branches:
      - 'fix/**'
      - 'feature/**'
  pull_request:
    branches:
      - main
      - develop
      - 'releases/**'

jobs:
  test:
    name: Run test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 15.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2-beta
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn --frozen-lockfile
      - run: yarn test
